name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - id: build_and_publish_packages
        if: github.repository == 'iqtlabs/poseidon' && github.event_name == 'push'
          && startsWith(github.event.ref, 'refs/tags')
        name: Build and publish packages
        run: 'sudo apt-get update && \

          sudo apt-get install -yq --no-install-recommends curl gcc g++ libev-dev
          libyaml-dev python3-pip python3.8 python3.8-dev && \

          cd lib/poseidon_api && poetry build && poetry publish -u ${{ secrets.PYPI_USERNAME
          }} -p ${{ secrets.PYPI_TOKEN }} && cd ../../ && \

          cd lib/poseidon_cli && poetry build && poetry publish -u ${{ secrets.PYPI_USERNAME
          }} -p ${{ secrets.PYPI_TOKEN }} && cd ../../ && \

          cd lib/poseidon_core && poetry build && poetry publish -u ${{ secrets.PYPI_USERNAME
          }} -p ${{ secrets.PYPI_TOKEN }} && cd ../../

          '
      - id: measurement-4
        name: Record Measurement After Build and publish packages
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Build and publish packages
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
